### ISSUE TITLE
Can not build on Android

### ISSUE THREAD

**Issue by longnguyen0410** [DRSchlaubi/contact_picker#11]
I got this error when build on Android:
Android/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/fluttercontactpicker-3.0.1/android/src/main/kotlin/me/schlaubi/fluttercontactpicker/ContactPicker.kt: (52, 280): Unresolved reference: stackTraceToString
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttercontactpicker:compileDebugKotlin'.
> Compilation error. See log for more details

Hope you fix it soon, thanks!

**Comment by longnguyen0410** [comment]
I fixed by updated kotlin version :)

**Comment by DRSchlaubi** [comment]
Yes stackTraceToString() was added in Kotlin 1.4.0
