### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by SpencerRiddering** [DRSchlaubi/contact_picker#2]
Not sure why this is occuring. 

I/flutter ( 7657): Caught error: MissingPluginException(No implementation found for method pickPhoneContact on channel me.schlaubi.contactpicker)
I/flutter ( 7657): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
I/flutter ( 7657): <asynchronous suspension>
I/flutter ( 7657): #1      FlutterContactPicker.pickPhoneContact (package:fluttercontactpicker/fluttercontactpicker.dart:12:22)

My code: 

```
final PhoneContact contact = await FlutterContactPicker.pickPhoneContact();
```

pubspec.yaml 
```
fluttercontactpicker: ^2.3.0
```

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/spencer/git/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/spencer/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/spencer/Android/Sdk
    • Java binary at: /home/spencer/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/spencer/opt/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Pixel 2 • FA7AH1A06907 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by viplifes** [comment]
Invalid channel name specified here - 
https://github.com/DRSchlaubi/contact_picker/blob/master/ios/Classes/SwiftFlutterContactPickerPlugin.swift#L11

**Comment by SpencerRiddering** [comment]
Hi @viplifes , I see the invalid channel name you referenced, but I'm testing on Android and the channel name in the Kotlin code looks correct. I've corrected the Swift file you mentioned just to be sure and nothing has changed. 

Note that I have done flutter clean, and pub get just to make sure there is no stale data hanging around.

**Comment by hellokugo** [comment]
I face the same error,Android can work , but iOS not.

**Comment by DRSchlaubi** [comment]
I forogot to push it to github but there is 2.3.2 now which should fix iOS too

**Comment by hellokugo** [comment]
> I forgot to push it to GitHub but there is 2.3.2 now which should fix iOS too

great，update work!!! Thanks~

**Comment by SpencerRiddering** [comment]
Thank you. This fixed the issue I was having.
