### ISSUE TITLE
I always fail to run with an error description in the flutter contact picker

### ISSUE THREAD

**Issue by irvanthole** [DRSchlaubi/contact_picker#21]
This problem only exists when I run it on Android, for iOS there is no problem, I run it smoothly.
This is an error display when I try to run it :

e: /Users/yohanescatur/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/fluttercontactpicker-4.2.1/android/src/main/kotlin/me/schlaubi/fluttercontactpicker/ContactPicker.kt: (52, 280): Unresolved reference: stackTraceToString

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttercontactpicker:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

can you help me find this problem?

**Comment by DRSchlaubi** [comment]
This looks like you use an earlier version of Kotlin than 1.4 can you please check your gradle version and set kotlin to 1.4.21?

**Comment by irvanthole** [comment]
> This looks like you use an earlier version of Kotlin than 1.4 can you please check your gradle version and set kotlin to 1.4.21?

I have updated the gradle to the newest. but still it can't be run should i install everything from scratch?

**Comment by irvanthole** [comment]
> This looks like you use an earlier version of Kotlin than 1.4 can you please check your gradle version and set kotlin to 1.4.21?

its work for me, thanks.
