### ISSUE TITLE
Make nullsafety the default version

### ISSUE THREAD

**Issue by DRSchlaubi** [DRSchlaubi/contact_picker#25]
Currently needs `meta` and `plugin_platform_interface` to do the same

**Comment by firatcetiner** [comment]
@DRSchlaubimet, plugin_platform_interface, and js packages have been opted-in into null-safety. Are you able to migrate the contact_picker_platform_interface and contact_picker_web into null safety as well? I can offer a little help if you need it.

**Comment by DRSchlaubi** [comment]
There already is a null sagte version: https://pub.dev/packages/fluttercontactpicker/versions/4.3.0-nullsafety.5

I can't use my pc right now so it might take some time

**Comment by DRSchlaubi** [comment]
There already is a null sagte version: https://pub.dev/packages/fluttercontactpicker/versions/4.3.0-nullsafety.5

I can't use my pc right now so it might take some time

**Comment by DRSchlaubi** [comment]
There already is a null sagte version: https://pub.dev/packages/fluttercontactpicker/versions/4.3.0-nullsafety.5

I can't use my pc right now so it might take some time

**Comment by firatcetiner** [comment]
> There already is a null sagte version: https://pub.dev/packages/fluttercontactpicker/versions/4.3.0-nullsafety.5
> 
> I can't use my pc right now so it might take some time

Yeah but it depends on `plugin_platform_interface ^1.1.0-nullsafety.1`, thus conflicts with some other packages. For example: `firebase_messaging`

**Comment by DRSchlaubi** [comment]
Gott my PC working again will publish new version shortly

**Comment by firatcetiner** [comment]
@DRSchlaubi The current Dart SDK version is `2.12.0` on the latest Flutter stable channel and since this plugin depends on `>=2.12.1 <3.0.0` it cannot be used right now on the stable channel.

**Comment by DRSchlaubi** [comment]
I just took the version which snap installed me I lowered the sdk constraints to 2.12.0

**Comment by firatcetiner** [comment]
Awesome. Thanks for the very quick responses!
