### ISSUE TITLE
Unimplemented error

### ISSUE THREAD

**Issue by firatcetiner** [DRSchlaubi/contact_picker#28]
I got this error while trying to pick contacts using this library `(4.3.1)`: 

`Unhandled Exception: UnimplementedError: pickPhoneContacts() has not been implemented`

A similar error is thrown whenever I use some other components from the package, for example, `available`.  I tested it for both iOS and Android devices.

I also tried to use version `4.2.1` but the result is the same.

**Comment by DRSchlaubi** [comment]
As the docs state both methods are only available using fitter web. On Android you can use `pickFullContact()` and on all platforms you can use `pickPhoneConact()` and `pickEmailContact()`
