### ISSUE TITLE
pickEmailContact never completes if pressing BACK on Android

### ISSUE THREAD

**Issue by kaciula** [DRSchlaubi/contact_picker#29]
Hi.

Thank you for the useful plugin.

On Android, if I start pickEmailContact and await and the user does not choose a contact but presses BACK, the code hangs indefinitely. 

I would suggest you detect BACK press and return a null contact. Otherwise, define an encapsulating object that has a success boolean value along with the contact (if chosen)

**Comment by DRSchlaubi** [comment]
I guess i don't complete the future if the intent never returns will see how to fix it later this day
