### ISSUE TITLE
One method, all info

### ISSUE THREAD

**Issue by aleZil** [DRSchlaubi/contact_picker#3]
Hi!
Great plugin! I have two suggestions:

- could you please divide fullName in name and surname?
- could you please provide a single method to obtain (in one call) name, surname, phone number and email?

Thanks a lot!

**Comment by DRSchlaubi** [comment]
I started working on this a while ago and the android implementation should be finished now, I will try to finish iOS implementation tomorrow to get this fixed
You can see the progress [here](https://github.com/DRSchlaubi/contact_picker/tree/feature/full-contact)

**Comment by aleZil** [comment]
Thank you for your support! 

After updating the version of your plugin i found out there was a bug. I have resolved it locally, by replacing nick**t**Name with nickName (notice the T after "nick").

**Comment by DRSchlaubi** [comment]
Damn it I thought i fixed that
