### ISSUE TITLE
Cast exception when import contact

### ISSUE THREAD

**Issue by thaodersar** [DRSchlaubi/contact_picker#30]
I got this cast error when import contact:
Unhandled Exception: type 'Future<Map<dynamic, dynamic>?>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>' in type cast
[        ] E/flutter ( 5697): #0      MethodChannelContactPicker.pickPhoneContact (package:contact_picker_platform_interface/src/method_channel_contact_picker.dart:17:11)
[        ] E/flutter ( 5697): #1      FlutterContactPicker.pickPhoneContact (package:fluttercontactpicker/src/interface.dart:29:12)

It cause by this code:

`Future<FullContact> pickFullContact({bool askForPermission = true}) async =>
      FullContact.fromMap((await (_channel.invokeMethod<Map<dynamic, dynamic>>(
              'pickContact', {'askForPermission': askForPermission})
          as FutureOr<Map<dynamic, dynamic>>)));`

**Comment by DRSchlaubi** [comment]
Which version are you on?

**Comment by thaodersar** [comment]
Hi, I think error n 4.3.3.
But after upgrade to 4.4.0 today issue is fixed. So I close this issue.

Thank you
