### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by techwithsam** [DRSchlaubi/contact_picker#36]
![Screenshot 2021-06-23 154553_LI](https://user-images.githubusercontent.com/42917957/123127912-9a80e280-d442-11eb-9b52-7bdcb58c1010.jpg)

**Comment by DRSchlaubi** [comment]
Don't use 4.4.0 use 4.5.0

**Comment by techwithsam** [comment]
![Screenshot 2021-06-24 003044](https://user-images.githubusercontent.com/42917957/123180591-7a254800-d483-11eb-9020-d2960eefef67.png)

**Comment by DRSchlaubi** [comment]
What flutter version is used?

**Comment by techwithsam** [comment]
Flutter: 2.2.2

**Comment by DRSchlaubi** [comment]
```yaml
dependency_overrides:
  meta: "1.3.0"
```
try this

**Comment by DRSchlaubi** [comment]
Fixed in `4.5.1`

**Comment by techwithsam** [comment]
Thanks
