### ISSUE TITLE
Kotlin Experimental Feature Issue

### ISSUE THREAD

**Issue by hashweather** [DRSchlaubi/contact_picker#38]
Hello, thanks for the time taken to make this amazing library.

However, I couldn't get it to work.

This is what I keep getting:

`e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttercontactpicker-4.5.0\android\src\main\kotlin\me\schlaubi\fluttercontactpicker\ContactPicker.kt: (22, 115): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'
`

**Comment by DRSchlaubi** [comment]
I can't reporduce this with `flutter build` can you tell me which command you used

**Comment by DRSchlaubi** [comment]
Fixed in `4.5.1`

**Comment by DRSchlaubi** [comment]
Whoops wrong issue

**Comment by hashweather** [comment]
I used this command

`flutter run lib/main.dart --no-sound-null-safety`

Here is my android  config

```
defaultConfig{
 minSdkVersion 20
 targetSdkVersion 30
}
```

**Comment by robert-virkus** [comment]
I have the same breaking issue, downgrading to 4.4.0 and `flutter clean` fixed it for me:
```
  fluttercontactpicker: 4.4.0
```

**Comment by DRSchlaubi** [comment]
> I have the same breaking issue, downgrading to 4.4.0 and `flutter clean` fixed it for me:
> 
> ```
>   fluttercontactpicker: 4.4.0
> ```

But 4.4.0 is not supported anymore and shouldn't be used

My guess is that you havea kotlin version before 1.5 in your app in which that function is marked as experimental so make sure to use kotlin 1.5 as well

**Comment by robert-virkus** [comment]
Thanks for your feedback!

Indeed my previous kotlin-version was 1.4.31 in `android/build.gradle', upgrading to `1.5.0` fixed the problem.

```gradle
buildscript {
    ext.kotlin_version = '1.5.0'
   [...]
}
```

Currently the fluttercontractpicker documentation states: "Note: This plugin requires at least Kotlin 1.4.0 to compile". 
It would be nice to update this requirement and also specify how to do it.

**Comment by hashweather** [comment]
Thanks @DRSchlaubi, increasing my kotlin version to `1.5` fixed it.

**Comment by DRSchlaubi** [comment]
> Thanks for your feedback!
> 
> Indeed my previous kotlin-version was 1.4.31 in `android/build.gradle`, upgrading to `1.5.0` fixed the problem.
> 
> ```groovy-gradle
> buildscript {
>     ext.kotlin_version = '1.5.0'
>    [...]
> }
> ```
> 
> Currently the fluttercontractpicker documentation states: "Note: This plugin requires at least Kotlin 1.4.0 to compile".
> It would be nice to update this requirement and also specify how to do it.

The readme got updated in https://github.com/DRSchlaubi/contact_picker/commit/6d7169f98d8148131e372a03eab34fe3c0083ecf
