### ISSUE TITLE
Unresolved reference "lowercase"?

### ISSUE THREAD

**Issue by alex-melnyk** [DRSchlaubi/contact_picker#39]
![image](https://user-images.githubusercontent.com/30177329/124294767-bda54380-db60-11eb-8581-bab38281007b.png)
I found that issue while trying to build Android version of my app with "fluttercontactpicker 4.5.1"
Should it be **toLowerCase()** method?

**Comment by DRSchlaubi** [comment]
toLowerCase() got deprecated in Kotlinc 1.5 and replaced by lowercase() you need to update your version of kotlin as stated in the readme

Duplicates #38

**Comment by DRSchlaubi** [comment]
Duplicate of #38
