### ISSUE TITLE
Unable to build in 2.7.0

### ISSUE THREAD

**Issue by SatyaMirthipati** [DRSchlaubi/contact_picker#46]

**Comment by DRSchlaubi** [comment]
Could you please share more information on how the build fails?

**Comment by SatyaMirthipati** [comment]
Ensure that you have a dependency on the Kotlin standard library 
build fails with this error

**Comment by DRSchlaubi** [comment]
That's not he full error, how do you build?

**Comment by SatyaMirthipati** [comment]
i resolved that by changing gradle.properties & kotlin version 
thank you
