### ISSUE TITLE
[android] minimal permission

### ISSUE THREAD

**Issue by daadu** [DRSchlaubi/contact_picker#48]
Recently I switched from `contact_picker` to this plugin and noticed that it includes "READ_CONTACTS" permission in it's manifest. This permission is only needed if you fetch full contact.

Therefore, I suggest either of following changes to communicate this properly.
- remove this permission from lib manifest and add note in readme to add it manually if user wants to use full contact.
- keep this permission and tell user how to [remove this permission from app manifest](https://stackoverflow.com/a/37459329) if they are not using this feature.

I would like to make this changes based on which approach is decided.

**Comment by DRSchlaubi** [comment]
It is required on any Xiaomi devices I used and on Stock android when using android 11+, which is why it is in the manifest

**Comment by daadu** [comment]
Went through [the official doc for picking contact via intent](https://developer.android.com/guide/components/intents-common#Contacts):

> When you retrieve the contact URI using the above intent, you generally don't need the READ_CONTACTS permission to read basic details for that contact, such as display name and whether the contact is starred. However, if you're trying to read more specific data about a given contact—such as their phone number or email address—you need the READ_CONTACTS permission

Therefore you're right it is required to get the mobile number as well.

**Comment by daadu** [comment]
My bad. Feel free to close this issue.

**Comment by DRSchlaubi** [comment]
Also having the permission in the manifest shouldn't be an issue, as long as you don't call requestPermission() the user shouldn't notice it, without opening the app info settings
