### ISSUE TITLE
这是啥原因

### ISSUE THREAD

**Issue by lovachen** [DRSchlaubi/contact_picker#5]
Compiler message:
../lib/fluttercontactpicker.dart:209:88: Error: The getter 'nicktName' isn't defined for the class 'StructuredName'.
 - 'StructuredName' is from 'package:fluttercontactpicker/fluttercontactpicker.dart' ('../lib/fluttercontactpicker.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nicktName'.
    return 'StructuredName{firstName: $firstName, middleName: $middleName, nicktName: $nicktName, lastName: $lastName}';

**Comment by DRSchlaubi** [comment]
Could you try using `2.4.2`?

**Comment by DRSchlaubi** [comment]
Closed because of inactivity
