### ISSUE TITLE
No implementation found  error

### ISSUE THREAD

**Issue by Bugimz** [DRSchlaubi/contact_picker#56]
E/flutter (18603): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method pickPhoneContact on channel me.schlaubi.contactpicker)
E/flutter (18603): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:175
E/flutter (18603): <asynchronous suspension>
E/flutter (18603): #1      MethodChannelContactPicker._runCancellable (package:contact_picker_platform_interface/src/method_channel_contact_picker.dart:33:23)
E/flutter (18603): <asynchronous suspension>
E/flutter (18603): #2      MethodChannelContactPicker.pickPhoneContact (package:contact_picker_platform_interface/src/method_channel_contact_picker.dart:11:29)
E/flutter (18603): <asynchronous suspension>
E/flutter (18603):

my phone is xiaominote 10

**Comment by DRSchlaubi** [comment]
This sounds like a v1 embedding issue to me
