### ISSUE TITLE
request contact picker issue

### ISSUE THREAD

**Issue by gangadharashettypj** [DRSchlaubi/contact_picker#6]
When i try to open a view controller, i am getting the following warning and the contact book is not opening,

> Warning: Attempt to present <CNContactPickerViewController: 0x7fcc1151fb90> on <UINavigationController: 0x7fcc0c858a00> whose view is not in the window hierarchy!

Currently i am using fluttercontactpicker: 2.3.2 but in latest also facing the same issue.

when i gone through the code you are presenting on top of rootViewController, but there may be other view controllers on top of rootViewControllers, so i found the following fix, by presenting it on the top most presented viewController as shown below

> private func requestPicker(result: @escaping FlutterResult, type: String, neededProperty: String) {
        let controller = CNContactPickerViewController()
        pickerDelegate = ContactPickerDelegate(result: result, type: type)
        controller.delegate = pickerDelegate
        controller.displayedPropertyKeys = [neededProperty]
        var viewController = UIApplication.shared.delegate?.window??.rootViewController
        while ((viewController?.presentedViewController) != nil) {
            viewController = viewController?.presentedViewController;
        }
        viewController?.present(controller, animated: true, completion: nil)
    }

let me know if you have any other points related to this. If you find this fix is needed, please update it in the next release.

Thank you

**Comment by DRSchlaubi** [comment]
I don't really use iOS very often so i also did not test the ios part as much as the android part. Can you tell me which method of the plugin you used?

**Comment by gangadharashettypj** [comment]
Hi, 
You get this issue in any of the method, because its trying to push view on a controller which is not in top. So i added a loop whuch gets the latest presented view controller

**Comment by halldorr** [comment]
@gangadharashettypj do you have this working in iOS now? If so, do you have working code somewhere you'd be willing to share? The Android version works great but the iOS one does not for me.

**Comment by gangadharashettypj** [comment]
@halldorr yes, i have. But its old version. If you want i can go through the latest version n send you the PR

**Comment by DRSchlaubi** [comment]
Fixed by #10
